wordpress:
  build: .
  links: 
   - db
  ports:
   - "8080:80"
  environment:
    DB_NAME: wordpress
    DB_USER: admin
    DB_PASS: 1qaz2wsx..
    DB_HOST: 127.0.0.1
    DB_PORT: 3306
db:
  image: tutum/mariadb:latest
  environment:
    MARIADB_PASS: 1qaz2wsx..